[package]
name = "open-protocol-client"
version = "0.1.0"
edition = "2021"

[dependencies]
open-protocol = { workspace = true }
open-protocol-codec = { workspace = true }
thiserror = "2.0"
tokio = { version = "1", features = ["full"] }
flume = "0.11"
bytes = "1.10.0"
