[package]
name = "open-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
open-protocol-codec = { workspace = true }
open-protocol-codec-proc-macro = { workspace = true }
chrono = "0.4"
paste = "1.0"
