[package]
name = "open-protocol"
version = "0.1.0"
edition = "2021"
description = "Implementation of the Atlas Copco/Torque Open Protocol specification in Rust."
readme = "README.md"
license-file = "LICENSE"
homepage = "https://github.com/dezemand/rs-open-protocol"
repository = "https://github.com/dezemand/rs-open-protocol"

[dependencies]
open-protocol-codec = { workspace = true }
open-protocol-codec-proc-macro = { workspace = true }
chrono = "0.4"
paste = "1.0"
thiserror = "2.0"
