[package]
name = "open-protocol-codec-proc-macro"
version = "0.1.0"
edition = "2021"
description = "Procedural macros for deriving encode/decode implementations for Atlas Copco/Torque Open Protocol."
readme = "README.md"
license-file = "LICENSE"
homepage = "https://github.com/dezemand/rs-open-protocol"
repository = "https://github.com/dezemand/rs-open-protocol"

[lib]
proc-macro = true

[dependencies]
open-protocol-codec = { workspace = true }
quote = "1.0.37"
syn = { version = "2.0.79", features = ["full", "extra-traits"] }
proc-macro2 = "1.0"
thiserror = "2.0"
itertools = "0.14"