[package]
name = "open-protocol-codec-proc-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
open-protocol-codec = { workspace = true }
quote = "1.0.37"
syn = { version = "2.0.79", features = ["full", "extra-traits"] }
proc-macro2 = "1.0"
thiserror = "2.0"
