[package]
name = "open-protocol-mqtt-adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
sparkplug-rs = { version = "0.4" }
rumqttc = "0.24.0"
open-protocol-client = { workspace = true }
tokio = { version = "1", features = ["full"]  }
pretty_env_logger = "0.5"
log = "0.4.25"
