[package]
name = "open-protocol-mqtt-adapter"
version = "0.0.0"
edition = "2021"
description = "Helper library with encoding and decoding functionalities for Atlas Copco/Torque Open Protocol."
readme = "README.md"
license-file = "LICENSE"
homepage = "https://github.com/dezemand/rs-open-protocol"
repository = "https://github.com/dezemand/rs-open-protocol"

[dependencies]
sparkplug-rs = { version = "0.4" }
rumqttc = "0.24.0"
open-protocol-client = { workspace = true }
tokio = { version = "1", features = ["full"]  }
pretty_env_logger = "0.5"
log = "0.4.25"
